# Generated by Django 2.0.2 on 2018-04-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('street', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('identifier', models.IntegerField(default='')),
                ('state', models.NullBooleanField(default=None)),
                ('last_updated', models.DateField(default=None)),
                ('coordinate_x', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('coordinate_y', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
            ],
        ),
    ]
