# Generated by Django 2.0.2 on 2018-04-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlight',
            old_name='street',
            new_name='crossing',
        ),
        migrations.RenameField(
            model_name='trafficlight',
            old_name='identifier',
            new_name='idx',
        ),
        migrations.RemoveField(
            model_name='trafficlight',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='trafficlight',
            name='number',
        ),
    ]
