# Generated by Django 2.0.2 on 2018-04-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180405_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlight',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
