# Generated by Django 2.0.2 on 2018-04-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trafficlight_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlight',
            old_name='state',
            new_name='status',
        ),
    ]
