# Generated by Django 2.0.2 on 2018-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180405_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlight',
            name='status',
            field=models.IntegerField(default=''),
        ),
    ]
