# Generated by Django 2.0.2 on 2018-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180405_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlight',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
