# Generated by Django 2.0.4 on 2018-04-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('crossing', models.TextField(blank=True, null=True)),
                ('idx', models.IntegerField(default='')),
                ('status', models.TextField(default='')),
                ('coordinate_x', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('coordinate_y', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
            ],
        ),
    ]
