# Generated by Django 2.0.4 on 2018-04-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180406_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlight',
            name='id',
        ),
        migrations.AlterField(
            model_name='trafficlight',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
