# Generated by Django 2.0.4 on 2018-04-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180406_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlight',
            name='crossing',
        ),
    ]
