# Generated by Django 2.0.4 on 2018-04-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_trafficlightdetectors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlightdetectors',
            old_name='detector',
            new_name='crossingname',
        ),
        migrations.RemoveField(
            model_name='trafficlightdetectors',
            name='congestion_count',
        ),
        migrations.RemoveField(
            model_name='trafficlightdetectors',
            name='device',
        ),
        migrations.RemoveField(
            model_name='trafficlightdetectors',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='trafficlightdetectors',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='trafficlightdetectors',
            name='queue_length',
        ),
        migrations.RemoveField(
            model_name='trafficlightdetectors',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='trafficlightdetectors',
            name='vehicle_count',
        ),
        migrations.RemoveField(
            model_name='trafficlightdetectors',
            name='wait_time_avg',
        ),
        migrations.RemoveField(
            model_name='trafficlightdetectors',
            name='wait_time_max',
        ),
        migrations.AddField(
            model_name='trafficlightdetectors',
            name='timestamp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
