# Generated by Django 2.0.2 on 2018-03-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrafficLigt',
            new_name='TrafficLight',
        ),
    ]
