# Generated by Django 2.0.2 on 2018-03-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_data', '0002_auto_20180315_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlight',
            name='identifier',
            field=models.IntegerField(default=''),
        ),
    ]
